<style>
    h3{font-family: "Microsoft YaHei";margin-bottom: 30px;padding-right:40px;}
    h3 span{font-size: 14px;}
    .form-group input{max-width: 400px;}
    .form-group textarea{max-width: 400px;height:200px;}
    .form-group label{width:100px;}
    .form-group img{display:block;margin-top:10px;max-width: 400px;}
    .form-group .control-label{float:left;}
    .checkbox-inline input{position: relative;left:20px;}
    .check-box .checkbox-inline{float: left;}
    .has-error .control-label{position:relative;left:115px;}
    .form-change{width:150px; margin-right:10px;float:left}
    .form-group .label-change{float:left;}
    @media(max-width: 768px){
        .form-group label{text-align: right;}
    }
</style>
<h3>
    文章修改
    <div class="pull-right">
        <span>操作：</span>
        <a href="/admin/article/" class="btn btn-default">列表</a>
    </div>
</h3>
<form method="POST" enctype="multipart/form-data" class="form-horizontal" action="/admin/article/add/">
    <?php
    if (isset($errorMessage)):
        ?>
        <div class="form-group has-error">
            <label class="control-label">
                <?php echo $errorMessage; ?>
            </label>
        </div>
        <?php
    endif;
    ?>
    <div class="form-group">
        <label class="control-label">标题：</label>
        <div class="col-xs-8">
            <input class="form-control" value="<?php echo $this->model ? $this->model->getTitle() : ''; ?>" name="title" type="text"/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label">类型：</label>
        <div class="col-xs-8">
            <select name="sort">
                <?php foreach ($this->sort as $sort):?>
                <option value="<?php echo $sort->getId();?>" <?php echo $this->model->getSort_ids()==$sort->getId() ? 'selected = selected':''?>><?php echo $sort->getName();?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label">内容：</label>
        <div class="col-xs-8">
            <textarea class="form-control" name="body" id="intro"><?php echo $this->model ? $this->model->getBody() : ''; ?></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label">首字母：</label>
        <div class="col-xs-8">
            <input class="form-control" value="<?php echo $this->model ? $this->model->getLetter() : ''; ?>" name="letter" type="text"/>
        </div>
    </div>
    <div class="form-group check-box">
        <label class="control-label">推荐：</label>
        <label class="checkbox-inline">
            <input name="recommended" type="checkbox" id="commend" value="1" <?php echo $this->model ? ($this->model->getRecommended() ? 'checked = checked' : '') : ''; ?> />
        </label>
    </div>
    <div class="form-group">
        <label class="control-label"></label>
        <input type="hidden" value="<?php echo $this->model->getId();?>" name="id"/>
        <input class="btn btn-info" value="提交" name="submit"  type="submit"/>
    </div>
</form>


<iframe class="hidden" name="pic-frame" id="pic-frame"></iframe>
<script>
    var index = 0;
    var list = [{
            imgObj: $("#imgObj"),
            imgInput: $("#imgInput")
        }, {
            imgObj: $("#imgObj1"),
            imgInput: $("#imgInput1")
        }];
    $("#imgBtn").click(function() {
        index = 0;
    });
    $("#imgBtn1").click(function() {
        index = 1;
    });
    $("#imgBtn2").click(function() {
        index = 1;
    });
    $("#pic-frame").load(function() {
        var body = $(this.contentDocument).find("body");
        var pre = body.find("pre");
        var json;
        if (pre.size() > 0) {
            json = pre.html();
        } else {
            json = body.html();
        }
        if (!json || json == '') {
            return void 0;
        }
        try {
            json = eval('(' + json + ')');
            if (json.errno != 0) {
                alert(json.errmsg);
                return void 0;
            }
            list[index]['imgObj'].attr('src', json.data.url);
            list[index]['imgInput'].val(json.data.file);
        } catch (err) {
            alert("上传遇到问题，请联系技术人员处理。");
        } finally {
            $("#myUpload").modal('hide');
        }
    });
    $("#pic-frame2").load(function() {
        var body = $(this.contentDocument).find("body");
        var pre = body.find("pre");
        var json;
        if (pre.size() > 0) {
            json = pre.html();
        } else {
            json = body.html();
        }
        if (!json || json == '') {
            return void 0;
        }
        try {
            json = eval('(' + json + ')');
            if (json.errno != 0) {
                alert(json.errmsg);
                return void 0;
            }
            $("#imgObj2").attr('src', json.data.url);
            $("#imgInput2").val(json.data.file);
        } catch (err) {
            alert("上传遇到问题，请联系技术人员处理。");
        } finally {
            $("#myUpload").modal('hide');
        }
    });
</script>