<style>
    h3{font-family: "Microsoft YaHei";margin-bottom: 30px;padding-right:40px;}
    h3 span{font-size: 14px;}
    .form-group input{max-width: 400px;}
    .form-group textarea{max-width: 400px;height:200px;}
    .form-group label{width:100px;}
    .form-group .control-label{float:left;}
    .checkbox-inline input{position: relative;left:20px;}
    .check-box .checkbox-inline{float: left;}
    .has-error .control-label{position:relative;left:115px;}
    @media(max-width: 768px){
        .form-group label{text-align: right;}
    }
</style>
<h3>
    修改管理员权限
    <div class="pull-right">
        <span>操作：</span>
        <a href="/admin/admingroup/add/" class="btn btn-default">添加</a>
    </div>
</h3>
<form method="POST" enctype="multipart/form-data" class="form-horizontal" action="/admin/admingroup/edit/">
    <?php
    if(isset($errorMessage)):
    ?>
        <div class="form-group has-error">
            <label class="control-label">
                <?php echo $errorMessage;?>
            </label>
        </div>
    <?php
    endif;
    ?>
    <div class="form-group">
        <label class="control-label">管理员组：</label>
        <div class="col-xs-8">
            <input class="form-control" value="<?php echo $this->model ? $this->model->getGroup_name() : '';?>" name="group_name" id="group_name" type="text"/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label">权限：</label>
        <div class="col-xs-8">
            <textarea class="form-control" name="purview" id="purview" rows="3"><?php echo $this->model ? $this->model->getPurview() : '';?></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label"></label>
        <input type="hidden" name="id" value="<?php echo $this->model ? $this->model->getId() : ''?>" />
        <input class="btn btn-info" value="提交" name="submit" id="submit" type="submit"/>
    </div>
</form>