<style>
    h3{font-family: "Microsoft YaHei";margin-bottom: 30px;padding-right:40px;}
    h3 span{font-size: 14px;}
    .tb-center{text-align: center;}
    td .ellipsis{text-overflow:ellipsis;overflow:hidden;width:100%;white-space:nowrap;}
    @media(max-width: 1280px){
        #search .control-label{padding:7px 0 0 0;}
    }
</style>
<h3>
    <?php echo $this->title;?>
    <div class="pull-right">
    </div>
</h3>
<table class="table table-striped" style="table-layout: fixed;">
    <thead>
    <th style="width:40px;">ID</th>
    <th>栏目标题</th>
    <th>目录</th>
    <th>操作</th>
    </thead>
<?php foreach ($this->list as $sort):?>
    <tr>
        <form action="/admin/sort/edit/" method="post">
            <td>
                <div class="ellipsis">
                     <input type="hidden" name="id" value="<?php echo $sort->getId();?>" />
                </div>
            </td>
            <td>
                <div class="ellipsis">
                    <input type="text" name="name" id="name" value="<?php echo $sort->getName();?>" class="form-control" style="width:300px;"/>
                </div>

            </td>
            <td>
                 <div class="ellipsis">
                    <input type="text" name="mappath" id="mappath" value="<?php echo $sort->getMappath();?>" class="form-control" style="width:300px;"/>
                </div>
            </td>
            <td><input type="submit" name="sub" id="sub" class="btn btn-default" value="修改"/></td>
        </form>
    </tr>
<?php endforeach; ?>


    <tr>
        <form action="/admin/sort/add/" method="post">
        <td></td>
        <td><input type="text" name="name" id="name" value="" class="form-control" style="width:300px;"/></td>
        <td><input type="text" name="mappath" id="mappath" value="" class="form-control" style="width:300px;"/></td>
        <td><input type="submit" name="sub" id="sub" class="btn btn-default" value="添加"/></td>
         </form>
    </tr>
</table>