<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>joeytime</title>
        <link rel="apple-touch-icon" href="/apple-touch-icon.png"/>
        <link href="/style/dist/common.css" type="text/css" rel="stylesheet">
        <link href="/style/dist/index/index.css" type="text/css" rel="stylesheet">
        <script type="text/javascript" src="/script/dist/lib/jquery.js"></script>
        <script type="text/javascript" src="/script/dist/base/base.js"></script>
    </head>
    <body>
    <div class="header">
        <div class="wraper">
                <a href="/" class="logo"><img src="/image/logo.png" alt="joeytime" width="268" height="87"/></a>
                <form id="form-search" action="/search/" method="get" class="ico search">
                        <input id="search" type="text" autocomplete="off" class="text" name="keyword" value="请输入文章名称">
                        <input type="submit" value="搜索" class="submit">
               </form>
        </div>
    </div>
    <div class="wraper share">
           <div id="baidu-share" class="ico"></div>
    </div>

