<div class="p-item">
        <ul class="mr">
            <li><a href="/life/" <?php if(isset($this->sort) && $this->sort == 'life'):?> class="curr"<?php endif;?> >life</a></li>
            <li><a href="/work/" <?php if(isset($this->sort) && $this->sort == 'work'):?> class="curr"<?php endif;?>>work</a></li>
            <li><a href="/photo/" <?php if(isset($this->sort) && $this->sort == 'photo'):?> class="curr"<?php endif;?>>phote</a></li>
            <li class="last"><a href="/sentence/"  <?php if(isset($this->sort) && $this->sort == 'sentence'):?> class="curr"<?php endif;?>>sentence</a></li>
        </ul>
</div>