<style>
    h3{font-family: "Microsoft YaHei";margin-bottom: 30px;padding-right:40px;}
    h3 span{font-size: 14px;}
    .form-group input{max-width: 400px;}
    .form-group textarea{max-width: 400px;height:200px;}
    .form-group label{width:100px;}
    .form-group img{display:block;margin-top:10px;max-width: 400px;}
    .form-group .control-label{float:left;}
    .checkbox-inline input{position: relative;left:20px;}
    .check-box .checkbox-inline{float: left;}
    .has-error .control-label{position:relative;left:115px;}
    .form-change{width:150px; margin-right:10px;float:left}
    .form-group .label-change{float:left;}
    @media(max-width: 768px){
        .form-group label{text-align: right;}
    }
</style>
<h3>
    心情短语添加
    <div class="pull-right">
        <span>操作：</span>
        <a href="/admin/sentence/" class="btn btn-default">列表</a>
    </div>
</h3>
<form method="POST" enctype="multipart/form-data" class="form-horizontal" action="/admin/sentence/add/">
    <?php
    if (isset($errorMessage)):
        ?>
        <div class="form-group has-error">
            <label class="control-label">
                <?php echo $errorMessage; ?>
            </label>
        </div>
        <?php
    endif;
    ?>
    <div class="form-group">
        <label class="control-label">类型：</label>
        <div class="col-xs-8">
            <select name="sort">
                <?php foreach ($this->sort as $sort):?>
                <option value="<?php echo $sort->getId();?>"><?php echo $sort->getName();?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label">内容：</label>
        <div class="col-xs-8">
            <textarea class="form-control" name="body" id="intro"></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label">首字母：</label>
        <label class="col-xs-8">
            <input name="letter" id="letter" class="form-control" />
        </label>
    </div>
    <div class="form-group check-box">
        <label class="control-label">推荐：</label>
        <label class="checkbox-inline">
            <input name="recommended" type="checkbox" id="commend"/>
        </label>
    </div>
    <div class="form-group">
        <label class="control-label"></label>
        <input class="btn btn-info" value="提交" name="submit" id="submit" type="submit"/>
    </div>
</form>


<iframe class="hidden" name="pic-frame" id="pic-frame"></iframe>
