<dl class="links">
    <dt>友情链接：</dt>
    <dd>
        <a href="http://www.ip138.com/" target="_blank">iP138查询网</a>
        <a href="http://www.3533.com/" target="_blank">3533手机世界</a>
        <a href="http://www.yy138.com/" target="_blank">手机应用下载</a>
        <a href="http://www.shoujiwan.com/" target="_blank">手机玩</a>
        <a href="http://www.shuaji.com/" target="_blank">刷机网</a>
    </dd>
</dl>