<?php
    $this->display("public/header.phtml");
?>

<div class="wraper wraper-index">
	<ul class="index-sort">
            <li><a href="/life/"><img src="image/game.png" alt="生活专区" width="225" height="80"/></a></li>
            <li><a href="/work/"><img src="image/bag.png" alt="工作专区" width="225" height="80"/></a></li>
            <li><a href="/photo/"><img src="image/activation.png" alt="图片" width="225" height="80"/></a></li>
            <li><a href="/sentence/"><img src="image/activation.png" alt="图片" width="225" height="80"/></a></li>
	</ul>
</div>



<?php
    $this->display("public/footer.phtml");
?>